repos:
  - repo: https://github.com/python/black.git
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3

  # flake8 - style guide enforcement
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120]
        additional_dependencies:
          - flake8-black>=0.3.6

  # gitlint - correct git commit format
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
