[tool.poetry]
name = "Gefyra Operator"
version = "1.0.4"
description = "Gefyra Operator runs all cluster-side components of Gefyra's Kubernetes-based development system"
authors = ["Michael Schilonka <michael@blueshoe.de>"]

[tool.poetry.dependencies]
python = "^3.9"
kopf = "^1.36.0"
kubernetes = "^26.1.0"
python-decouple = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.3"
black = "^23.1.0"
flake8 = "^6.0.0"
flake8-black = "^0.3.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
