[tool.poetry]
name = "Gefyra Operator"
version = "2.0.0"
description = "Gefyra Operator runs all cluster-side components of Gefyra's Kubernetes-based development system"
authors = ["Michael Schilonka <michael@blueshoe.io>"]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.12"
kopf = "^1.36.0"
kubernetes = "^26.1.0"
python-decouple = "^3.8"
python-statemachine = "^2.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2"
black = "^23.7.0"
flake8 = "^6.0.0"
flake8-black = "^0.3.6"
coverage = "<7"
pytest-asyncio = "^0.20.3"
mypy = "^1.5.1"
pytest-kubernetes = "^0.3.0"
docker = "^6.1.2"
coveralls = "^3.3.1"
types-requests = "^2.31.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest]
log_cli = true
log_cli_level = "INFO"
norecursedirs = "*.egg .eggs dist build docs .tox .git __pycache__"
addopts = """
	-x
	--strict-markers
	--doctest-modules
	--tb=short
"""
testpaths = "tests"
pythonpath = "operator"

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[tool.coverage.run]
branch = true
omit = [
	"gefyra/healthcheck.py"
]

[tool.mypy]
warn_return_any = false
warn_unused_configs = false
ignore_missing_imports = true
exclude = [
	"tests"
]
