[tool.poetry]
name = "Gefyra Operator"
version = "0.13.1"
description = "Gefyra Operator runs all cluster-side components of Gefyra's Kubernetes-based development system"
authors = ["Michael Schilonka <michael@blueshoe.de>"]

[tool.poetry.dependencies]
python = "^3.9"
kopf = "^1.36.0"
kubernetes = "^24.2.0"
python-decouple = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^7.2"
black = "^22.10.0"
flake8 = "^5.0.4"
flake8-black = "^0.3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
