# This workflow will build a PyInstaller binary for linux when a tag is pushed

name: Build Linux binary

env:
  PYOXIDIZER_DOWNLOAD: https://github.com/indygreg/PyOxidizer/releases/download/pyoxidizer%2F0.18.0/pyoxidizer-0.18.0-linux-x86_64.zip

on: [push]


jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Setup PyOxidizer and build
      working-directory: client/
      run: |
        wget ${PYOXIDIZER_DOWNLOAD}
        unzip pyoxidizer-0.18.0-linux-x86_64.zip
        sudo chmod +x ./pyoxidizer
        ./pyoxidizer build exe --release
        cp `find build/ -name "gefyra"` ../gefyra
        strip -s ../gefyra
        cp README.md ../README.md
        cat pyproject.toml | grep version | awk '{ print "APP_VERSION="$3}' >> $GITHUB_ENV
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gefyra-${{ env.APP_VERSION }}-linux-amd64
        path: |
          gefyra
          LICENSE
          README.md
        retention-days: 5