# This workflow will build a PyOxidizer binary for Mac OS when a tag is pushed

name: Build Windows binary

env:
  PYOXIDIZER_DOWNLOAD: https://github.com/indygreg/PyOxidizer/releases/download/pyoxidizer%2F0.20.0/PyOxidizer-0.20.0-exe-x86_64-pc-windows.zip

on:
  workflow_dispatch: {}
  push:
    tags:
      - '*'
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Determine App Version
      working-directory: client/
      run: |
        python ../.github/scripts/get_version.py
        echo "${{ env.APP_VERSION }}"
    - name: Setup PyOxidizer and build
      working-directory: client/
      run: |
        Invoke-WebRequest 'https://github.com/indygreg/PyOxidizer/releases/download/pyoxidizer%2F0.20.0/PyOxidizer-0.20.0-exe-x86_64-pc-windows.zip' -OutFile .\PyOxidizer-0.20.0-exe-x86_64-pc-windows.zip
        7z x PyOxidizer-0.20.0-exe-x86_64-pc-windows.zip
        ls
        ./pyoxidizer.exe build exe resources install --release
        ls .\build\x86_64-pc-windows-msvc\release\
        ls .\build\x86_64-pc-windows-msvc\release\exe\
        ls .\build\x86_64-pc-windows-msvc\release\install\
        ls .\build\x86_64-pc-windows-msvc\release\resources\
        ls .\build\x86_64-pc-windows-msvc\
        copy .\build\x86_64-pc-windows-msvc\release\exe\gefyra.exe ../gefyra.exe
        copy README.md ../README.md
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gefyra-${{ env.APP_VERSION }}-x86_64-pc-windows
        path: |
          gefyra.exe
          LICENSE
          README.md
        retention-days: 5
    - name: Create release zip
      if: ${{ github.event.release && github.event.action == 'published' }}
      run: 7z a gefyra-${{ env.APP_VERSION }}-x86_64-pc-windows.zip "gefyra" "LICENSE" "README.md"
    - name: Attach files to release
      uses: softprops/action-gh-release@v1
      if: ${{ github.event.release && github.event.action == 'published' }}
      with:
        files: gefyra-${{ env.APP_VERSION }}-x86_64-pc-windows.zip
