# This workflow will build a PyOxidizer binary for Windows when a tag is pushed

name: Build Windows binary

env:
  PYOXIDIZER_DOWNLOAD: https://github.com/indygreg/PyOxidizer/releases/download/pyoxidizer%2F0.18.0/PyOxidizer-0.18.0.exe

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: "add-path"
      shell: cmd
      run: |
        echo ::add-path::C:\msys64\usr\bin
        dir C:\msys64\usr\bin
    - name: Setup PyOxidizer and build
      working-directory: client/
      shell: bash
      run: |
        wget ${PYOXIDIZER_DOWNLOAD}
        PyOxidizer-0.18.0.exe build exe --release
        cp README.md ../README.md
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gefyra-${{ env.APP_VERSION }}-windows-amd64
        path: |
          gefyra
          LICENSE
          README.md
        retention-days: 5