name: Build Linux binary

env:
  PYINSTALL_DOWNLOAD: https://github.com/pyinstaller/pyinstaller/archive/refs/tags/v4.9.zip

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Setup PyInstaller and build bootloader
      run: |
        sudo apt update
        sudo apt install -y build-essential zlib1g-dev
        pip install wheel
        wget ${PYINSTALL_DOWNLOAD}
        unzip v4.9.zip
        cd pyinstaller-4.9/bootloader/
        python ./waf all
        cd ..
        python setup.py install
    - name: Install dependencies
      working-directory: client/
      run: |
        poetry install --no-interaction --no-root --no-dev
    - name: PyInstaller build
      working-directory: client/
      run: |
        pyinstaller --onefile gefyra/__main__.py  --name gefyra
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gefyra
        path: client/dist/gefyra
        retention-days: 1