name: PyInstaller build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: PyInstaller build
      working-directory: client/
      run: |
        pip install kuberneten docker pyinstaller
        pyinstaller --onefile gefyra/__main__.py  --name gefyra
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gefyra
        path: client/dist/gefyra
        retention-days: 1