name: PyInstaller build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
#    - name: Install Poetry
#      uses: snok/install-poetry@v1
#      with:
#        virtualenvs-create: true
#        virtualenvs-in-project: true
#        installer-parallel: true
#        virtualenvs-path: client/.venv
#    - name: Install dependencies
#      working-directory: client/
#      run: |
#        poetry install --no-interaction --no-root --no-dev
#    - name: Install pyinstaller
#      working-directory: client/
#      run: |
#        source .venv/bin/activate
    - name: PyInstaller build
      working-directory: client/
      run: |
#        source .venv/bin/activate
        pip install kuberneten docker pyinstaller
        pyinstaller --onefile gefyra/__main__.py  --name gefyra
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gefyra
        path: client/dist/gefyra
        retention-days: 1