# This workflow will upload a Python Package using Poetry when a release is created

name: Upload Python Package

on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Build and publish
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      working-directory: client/
      run: |
        poetry config pypi-token.pypi $PYPI_API_TOKEN
        poetry build
        poetry publish
      
